config/routes.rb
Rails.application.routes.draw do
  resources :members
  root :to => "members#index"
  get 'match' => 'match#index', :as => :new_match
  post 'match/rank' => 'match#rank', :as => :rank_match
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/match_controller.rb
class MatchController < ApplicationController

    def index
        @players = nil
        if Member.all.count > 1
            @players = Member.all
        end
    end
    def rank
        ApplyRankJob.perform_now(match_params)
    end
    
    def match_params
        params.permit(:player_one, :player_two, :winner)
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:name, :surname, :email, :birthday, :games_played, :rank)
    end
end

app/controllers/rank_controller.rb
class RankController < ApplicationController


    def initialize(hash_params)
        @player_one_id = hash_params[0]["player_one"]
        @player_two_id = hash_params[0]["player_two"]
        @winner_id = hash_params[0]["winner"]
    end

    def perform
        rank_players
    end

    def higher_rank 
        player_one.rank < player_two.rank ? player_one : player_two
    end

    def lower_rank 
        player_one.rank > player_two.rank ? player_one : player_two
    end

    def winner
        return nil if @winner_id.to_i < 1
        @winner ||= Member.find(@winner_id)
    end

    def player_one
        @player_one ||= Member.find(@player_one_id)
    end

    def player_two
        @player_two ||= Member.find(@player_two_id)
    end

    def rank_players
        new_lower_rank = lower_rank.rank
        new_higher_rank = higher_rank.rank

        if !winner
            if higher_rank.rank - 1 < lower_rank.rank
                new_lower_rank = lower_rank.rank - 1
            end

        elsif winner == lower_rank
            rank_difference = lower_rank.rank - higher_rank.rank
            new_lower_rank = lower_rank.rank - (rank_difference / 2).to_i
            new_higher_rank = higher_rank.rank + 1
        else
            return
        end
        rank_down(new_higher_rank, new_lower_rank)
    end

    def rank_down new_higher_rank, new_lower_rank
        lower_ranking = Member.where("rank >= ?", new_higher_rank).order("rank")
        ranking_index = new_higher_rank
        higher_rank.update("games_played = games_played + 1 AND rank = ?", new_higher_rank)
        lower_ranking.each do |lower_member|
            ranking_index += 1
            if(ranking_index == new_lower_rank)
                lower_rank.update("games_played = games_played + 1 AND rank = ?", ranking_index)
                ranking_index +=1
            end
            
            lower_member.update(rank: ranking_index)
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/match_helper.rb
module MatchHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/rank_helper.rb
module RankHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChessClub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/match/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Match</h1>
<% if @players != nil %>
    <%= form_tag("/match/rank", method: :post) do %>
        <p>Player One
        <%= select_tag(:player_one, options_from_collection_for_select(@players, :id, :name)) %></p>
        <p>Player Two
        <%= select_tag(:player_two, options_from_collection_for_select(@players, :id, :name)) %></p>
        <p>Winner
        <%= select_tag(:winner, options_from_collection_for_select(@players, :id, :name)) %></p>
        
        <%= submit_tag "Rank Match" %>
    <% end %>
<% else %>
    <h3>You need at least 2 members to start a match</h3>
<% end %>

app/views/match/rank.html.erb
<p> Thank you for playing </p>
You are being ranked

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.text_field :birthday %>
  </div>

  <div class="field">
    <%= form.label :games_played %>
    <%= form.number_field :games_played %>
  </div>

  <div class="field">
    <%= form.label :rank %>
    <%= form.number_field :rank %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New Match', new_match_path, class: "btn btn-info" %>
<h1>Members</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Email</th>
      <th>Birthday</th>
      <th>Games played</th>
      <th>Rank</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.surname %></td>
        <td><%= member.email %></td>
        <td><%= member.birthday %></td>
        <td><%= member.games_played %></td>
        <td><%= member.rank %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @member.surname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @member.birthday %>
</p>

<p>
  <strong>Games played:</strong>
  <%= @member.games_played %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @member.rank %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>